language: node_js

env:
  - DATABASE_URL=postgresql://postgres@localhost:5432/avoshopper

node_js:  
  - 12

before_script:
  - psql -c 'create database  avoshopper;' -U postgres
  - psql -U postgres -d avoshopper -a -f ./sql/tables.sql

services:
  - postgresql